### ISSUE TITLE
fouten in overzichtbeeld imkl 3.0

### ISSUE THREAD

**Issue by wernerpoel** [Informatievlaanderen/OSLOthema-imkl#14]
![image](https://github.com/Informatievlaanderen/OSLOthema-imkl/assets/153632547/e61d5245-f506-40cc-885e-33933125fe88)
Er staat een schrijffout 
INSPIRE-US: Nustvoorzieningnetwerkelement moet dit niet Nustvoorzieningnetwerkelement

**Comment by Jefliek** [comment]
Bedankt voor je feedback, we passen dit spoedig aan.
