### ISSUE TITLE
mangat

### ISSUE THREAD

**Issue by Rafvlm** [Informatievlaanderen/OSLOthema-imkl#7]
Het "gebruik" van mangat spreekt enkel over leidingen en niet over kabels.
In het model wordt ook geen gebruik gemaakt van de term "leiding" maar van "pijp".
Best aligneren zodat het "gebruik" refereert naar terminologie binnen het model.
cfr https://wegenenverkeer.data.vlaanderen.be/doc/implementatiemodel/kasten-cabines-behuizing/#Technische%20put
https://data.vlaanderen.be/doc/applicatieprofiel/kabels-en-leidingen/ontwerpstandaard/2023-10-05/#Mangat

**Comment by Jefliek** [comment]
Bedankt voor je feedback!
Dit is verwerkt, je kan het resultaat raadplegen op https://data.vlaanderen.be/doc/applicatieprofiel/kabels-en-leidingen/#Mangat
